spring:
  application:
    name: eureka-server
server:
  port: 7001
eureka:
  instance:
    hostname: peer2
  client:
    ## 如果不为true 将不会注册到另一台eureka
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:7000/eureka/
