spring:
  application:
    name: eureka-server
server:
  port: 7000
eureka:
  instance:
    hostname: peer1
  client:
    ## 如果不为true 将不会注册到另一台eureka
    register-with-eureka: true
    fetch-registry: true
    service-url:
      ## 这里如果有多个节点可以以逗号分隔 然后注册
      defaultZone: http://peer2:7001/eureka/
